import { Button, VerticalBox , HorizontalBox} from "std-widgets.slint";



export component AppWindow inherits Window {
    title: "Easy Config Wizard";
    preferred-width: 700px;
    preferred-height: 500px;
    background: #4d4d4d;
    callback button-pressed<=>button.clicked;
    callback button2-pressed<=>button2.clicked;
    callback button3-pressed<=>button3.clicked;

    HorizontalLayout {
        Rectangle {
            width: 200px;
            VerticalBox {
                spacing: 10px;
                Text {
                    text: "Easy Config Wizard";
                    font-size: 20px;
                    color: #ffffff;
                }
                button := Button {
                    height: 50px;
                    text: "This opens the Rust docs";
                }

                button2 := Button {
                    height: 50px;
                    text: "This opens Google";
                }

                button3 := Button {
                    height: 50px;
                    text: "This opens a new view";
                }

                Button {
                    height: 50px;
                    text: "Link 4";
                }

                Button {
                    height: 50px;
                    text: "Link 5";
                }

                Button {
                    height: 50px;
                    text: "Link 6";
                }
                Button {
                    height: 50px;
                    text: "Link 6";
                }
            }
        }
        Rectangle{
            
        }
    }
}
