import { Button, VerticalBox , HorizontalBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    callback request-increase-value();
    preferred-width: 1000px;
    height: 750px;
    background: #4d4d4d;
    VerticalBox {
        HorizontalBox {
            Text {
                text: "Hello this is a small text at the top of my application";
                font-size: 24px;
                color: #ffffff;
                horizontal-alignment: center;
            }
        }

        HorizontalBox {
            spacing: 50px;
            
            VerticalBox {
                spacing: 50px;

                Button {
                    text: "Link 1";
                }

                Button {
                    text: "Link 2";
                }

                Button {
                    text: "Link 3";
                }
            }

            VerticalBox {
                spacing: 50px;

                Button {
                    text: "Link 4";
                }

                Button {
                    text: "Link 5";
                }

                Button {
                    text: "Link 6";
                }
            }
        }
    }
}
